#DO NOT EDIT THIS FILE
import json
from flask import Blueprint, request
from sympy import sympify, Matrix,latex

eigenvector = Blueprint('eigenvector', __name__)

class Eigenvector:
   def __init__ (self):
      self.functions = [show_eigenvector]
      self.text = ""
      
   @staticmethod
   def show_eigenvector(func):
      output = Matrix(sympify(func)).eigenvects()
      return "\n".join([latex(a[2]) for a in output])

   @eigenvector.route('/apps/eigenvector',methods=["GET"])
   def run():
      expression = request.args["input"]
      return json.dumps({"text":"$$" + Eigenvector.show_eigenvector(expression) + "$$"})   

   @eigenvector.route('/apps/eigenvector/help',methods=["GET"])
   def help():
      return json.dumps({"text":"eigenvector help page"})     

   eigenvector_method = {'function_name':show_eigenvector,'keywords':['eigenvector']}
