#DO NOT EDIT THIS FILE
import json
from flask import Blueprint, request
from sympy import simplify as sympy_simplify, sympify, latex
from sympy.abc import *

simplify = Blueprint('simplify', __name__)

class Simplify:
   def __init__ (self):
      self.functions = [show_simplify]
      self.text = ""
      
   @staticmethod
   def show_simplify(func):
      func = sympify(func)
      return latex(sympy_simplify(func))

   @simplify.route('/apps/simplify',methods=["GET"])
   def run():
      expression = request.args["input"]
      return json.dumps({"text":"$$" + Simplify.show_simplify(expression) + "$$"})#Simplify.show_simplify(expression)   

   @simplify.route('/apps/simplify/help',methods=["GET"])
   def help():
      return json.dumps({"text":"simplify help page"})       

   simplify_method = {'function_name':show_simplify,'keywords':['simplify']}
