#DO NOT EDIT THIS FILE
from contextlib import redirect_stdout
import sys
from os import listdir
from os.path import isfile, join

def main(args):
   mypath = "modules"
   imports = """
from flask import Flask, render_template, request, session, url_for, make_response, redirect\n
from flask_sqlalchemy import SQLAlchemy\n
from core_app import *
             """
   init_app = """
app = Flask(__name__,template_folder=\"templates\",static_folder=\"static\")\n
app.register_blueprint(core_app)
              """
              
   modules = [f for f in listdir(mypath) if isfile(join(mypath, f)) and f!="__init__.py"]   
   imports_modules = "\n".join(["from modules." + f[:-3] + " import " + f[:-3] for f in modules])
   register_blueprints = "\n".join(["app.register_blueprint("+blueprint[:-3]+")" for blueprint in modules])
   main_function = """
if __name__ == '__main__':
   app.secret_key = "123"
   app.run(host='localhost', port=8080, debug=True)
   app.config['SESSION_TYPE'] = 'filesystem'
   app.config['SECRET_KEY'] = 'secret-key-goes-here'
   app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
   session.init_app(app)
   #db.create_all(app=app)
   #db.init_app(app)
   #db.create_all()
   #app.config.from_pyfile('settings.py')    
   app.debug = True                  
                   """
   with open('flask_app.py', 'w') as f:
      with redirect_stdout(f):
         print("#DO NOT EDIT THIS FILE")                    
         print(imports)
         print(imports_modules)   
         print(init_app)
         print(register_blueprints)
         print(main_function)
                     
if __name__=='__main__':
    main(sys.argv[1:]) 
